import{A as S,a as w,S as A,i as T}from"./assets/vendor-CMKjw0WY.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();(()=>{const e={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBth:document.querySelector("[data-menu-close]"),modalBtns:document.querySelectorAll(".modal-nav-link"),modal:document.querySelector("[data-modal]"),body:document.body};e.openModalBtn.addEventListener("click",t),e.closeModalBth.addEventListener("click",t),e.modalBtns.forEach(r=>{r.addEventListener("click",t)});function t(){e.modal.classList.toggle("is-open"),e.modal.classList.contains("is-open")?e.body.style.overflow="hidden":e.body.style.overflow=""}})();document.addEventListener("DOMContentLoaded",()=>{const e=[document.getElementById("theme-toggle"),document.getElementById("theme-toggle1")],t=document.querySelectorAll("[data-theme]"),r=localStorage.getItem("theme")||"light";t.forEach(n=>{n.setAttribute("data-theme",r)}),e.forEach(n=>{n.checked=r==="dark"}),e.forEach(n=>{n.addEventListener("change",()=>{const o=n.checked?"dark":"light";t.forEach(s=>{s.setAttribute("data-theme",o)}),e.forEach(s=>{s.checked=n.checked}),localStorage.setItem("theme",o)})})});const q="/js_110_Andrej89Ko/assets/10project2x-BvMudFNk.png",I="/js_110_Andrej89Ko/assets/8project2x-Beekt7gy.png",P="/js_110_Andrej89Ko/assets/7project2x-BnjIUlir.png",O="/js_110_Andrej89Ko/assets/6project2x-Co-_3AM6.png",_="/js_110_Andrej89Ko/assets/5project2x-BqgwRwZ7.png",C="/js_110_Andrej89Ko/assets/2project2x-CpyD6xhI.png",K="/js_110_Andrej89Ko/assets/1project2x-C868exiM.png",N=document.querySelector(".wrapContent"),y=document.querySelector(".projectBtnLoad"),R=[{src:q,name:"power pulse webservice"},{src:I,name:"vyshyvanka vibes Landing Page"},{src:P,name:"mimino website"},{src:O,name:"chego jewelry website"},{src:_,name:"fruitbox online store"},{src:C,name:"energy flow webservice"},{src:K,name:"starlight studio landing page"}];let i=0;const $=e=>`
    <li class="wrapContentItem">
      <img src="${e.src}" heigth="500" width="1000" alt="${e.name}">
      <p class="projectTextTech">react, java script, node js, git</p>
        <div class="wrapBtnText" data-theme="light">
                        <p class="projectTextTitle">${e.name}</p>
                        <a target="_blank" rel="noreferrer nofollow noopener" href="https://www.w3schools.com/js/default.asp"
                            class="projectBtnVisit">visit<svg class="arrSvg" height="24" width="24" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
    <path stroke-linejoin="round" stroke-linecap="round" stroke-miterlimit="4"
          stroke-width="3.5556"
          d="M3.111 28.889l25.778-25.778M28.889 3.111h-24M28.889 3.111v24"></path>
</svg></a>
                    </div>
    </li>`,D=e=>{let t=7,r=2;i<t&&(N.innerHTML+=R.slice(i,i+r).map(n=>$(n)).join(""),i+=r,i>=t&&(y.style.display="none"))};y.addEventListener("click",D);document.addEventListener("DOMContentLoaded",()=>{new S("#questions-list",{duration:250,showMultiple:!1,triggerClass:"ac-header"}).open(0)});document.addEventListener("DOMContentLoaded",()=>{const e=document.getElementById("contact-form"),t=document.getElementById("modal-together"),r=document.getElementById("modal-message"),n=document.querySelector(".close"),o=document.body,s=c=>{c.target===t&&(console.log("Outside click detected"),m())},a=c=>{console.log("Keydown event detected: ",c.key),c.key==="Escape"&&m()},m=()=>{console.log("Modal is closing"),t.classList.remove("is-open"),o.style.overflow="",j()},E=()=>{console.log("Adding event listeners"),n.addEventListener("click",m),window.addEventListener("click",s),window.addEventListener("keydown",a)},j=()=>{console.log("Removing event listeners"),n.removeEventListener("click",m),window.removeEventListener("click",s),window.removeEventListener("keydown",a)},h=()=>{console.log("Opening modal"),t.classList.add("is-open"),o.style.overflow="hidden",E()};e.addEventListener("submit",async c=>{c.preventDefault();const M=e.email.value.trim(),B=e.message.value.trim();try{(await fetch("https://portfolio-js.b.goit.study/api-docs/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:M,message:B})})).ok?(r.innerHTML=`
          <h3 class="modal-success">Thank you for your interest in cooperation!</h3>
          <p class="modal-info">The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.</p>`,e.reset()):r.textContent="There was an error with your request. Please try again.",h()}catch{r.textContent="An error occurred. Please try again.",h()}})});w.defaults.baseURL="https://portfolio-js.b.goit.study/api/";const u=document.querySelector(".btn-next"),p=document.querySelector(".btn-prev"),g=document.querySelector(".error-message"),V=document.querySelector(".reviews-navigation"),f=document.querySelector(".carousel-wrapper");let v;window.addEventListener("resize",l);document.addEventListener("keydown",e=>{e.key==="ArrowRight"?L():e.key==="ArrowLeft"&&b()});f.addEventListener("touchmove",k);f.addEventListener("mousemove",k);function L(){d.slideNext(),l()}function b(){d.slidePrev(),l()}function l(){d.isBeginning?p.classList.add("button-disabled"):p.classList.remove("button-disabled"),d.isEnd?u.classList.add("button-disabled"):u.classList.remove("button-disabled")}u.addEventListener("click",L);p.addEventListener("click",b);const d=new A(".swiper",{slidesPerView:1,spaceBetween:16,speed:800,breakpoints:{0:{slidesPerView:1},768:{slidesPerView:1},1280:{slidesPerView:2}}});async function F(){try{return(await w("/reviews")).data}catch{g.classList.remove("hidden"),V.classList.add("hidden"),U();return}}async function H(){const e=await F();if(e.length===0){g.classList.remove("hidden");return}f.insertAdjacentHTML("beforeend",z(e)),d.update(),l()}H();function z(e){return e.map(({review:t,author:r,avatar_url:n})=>`
      <div class="swiper-slide feedback-item">
        <p class="feedback-text">${t}</p>
        <div class="feedback-info">
          <img src="${n}" alt="${r}" class="feedback-avatar" />
          <span class="feedback-author">${r}</span>
        </div>
      </div>
    `).join("")}function U(){const e=new IntersectionObserver(J,{threshold:1});return e.observe(g),e}function J(e){e.forEach(t=>{t.isIntersecting&&T.error({message:"Reviews not found! Please try again later.",position:"topRight"})})}function k(){clearTimeout(v),v=setTimeout(l,200)}
//# sourceMappingURL=index.js.map
